# Generated by Django 6.0.3 on 2026-06-26 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_id_alter_postimage_id_alter_professor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark_users',
            field=models.ManyToManyField(blank=True, related_name='bookmark_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
