# Generated by Django 6.0.3 on 2026-06-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_id_alter_postimage_id_alter_professor_id'),
        ('posts', '0010_searchkeyword'),
    ]

    operations = [
    ]
